blog/apps/article/urls.py
from django.conf.urls import url
from article.views import Home, Publish, Summernoteimg,Details,Post_commentView

urlpatterns = [
    # 首页
    url(r'^$', Home.as_view(), name='home'),
    # 发帖页面
    url(r'^publish/$', Publish.as_view(), name='publish'),
    # summernote编辑器上传图片
    url(r'^summernoteimg/$', Summernoteimg.as_view(), name='summernoteimg'),
    # 详情
    url(r'^details/(?P<id>\d+)$', Details.as_view(), name='details'),
    # 评论
    url(r'^comment/(?P<post_pk>[0-9]+)/$', Post_commentView.as_view(), name='文章评论'),

]

blog/apps/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # summernote富文本编辑器
    url(r'^summernote/', include('django_summernote.urls')),
    # 上传部件自动调用的上传地址,ckeditor富文本编辑器
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 文章（帖子）
    url(r'^', include('article.urls', namespace='article')),
    # 用户
    url(r'^user/', include('user.urls', namespace='user')),
]

blog/templates/commen/footer.html
 <footer class="blog-footer">

        <div class="footer-social">
            <a href="#" target="_blank" class="fa fa-facebook"></a>
            <a href="#" target="_blank" class="fa fa-behance"></a>
            <a href="#" target="_blank" class="fa fa-twitter"></a>
            <a href="#" target="_blank" class="fa fa-linkedin"></a>
            <a href="#" target="_blank" class="fa fa-google-plus"></a>
            <a href="#" target="_blank" class="fa fa-youtube"></a>
        </div>
        <p>神圣的爱的精英，一个永恒的生命。</p>
        <p>2019.版权归娟娟所有。</p>
        <p>
            <a href="#">回到顶部</a>
        </p>
    </footer>

blog/templates/commen/header.html
{% load static %}
<header class="blog-header">
    <!--     Main Menu  -->
    <nav class="navbar navbar-expand-lg  center-navigation shadow-lg " id="center-navigation">
        <div class="container">
            <a class="navbar-brand" href="#"><img class="logo-dark d-sm-block d-lg-none "
                                                  src="{% static 'assets/images/logos.png' %}" alt="Logo-side"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="icofont icofont-navigation-menu"></i> </span>
            </button>

            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link page-scroll " href="{% url 'article:home' %}?tagname=0">python</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link page-scroll " href="{% url 'article:home' %}?tagname=1">前端</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link page-scroll " href="{% url 'article:home' %}?tagname=2">java</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link page-scroll header-logo d-none d-lg-block" href="{% url 'article:home' %}">
                            <img src="{% static 'assets/images/logos.png' %}" alt="Logo" class="img-fluid">
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:;" id="navbarDropdown4" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            其他
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown4">
                            <a class="dropdown-item" href="{% url 'article:home' %}?tagname=3">php</a>
                            <a class="dropdown-item" href="{% url 'article:home' %}?tagname=4">.net</a>
                            <a class="dropdown-item" href="{% url 'article:home' %}?tagname=5">数据库</a>
                            <a class="dropdown-item" href="{% url 'article:home' %}?tagname=6">测试</a>
                            <a class="dropdown-item" href="{% url 'article:home' %}?tagname=7">C++</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll " href="{% url 'article:publish' %}">发帖</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll " href="#">留言</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

blog/templates/commen/parent.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
          content="blog,resposive,sailor,bootstrap4,modern,html,html5,personal blog,agency blog,video,grid,Clean">
    <meta name="author" content="juanjuan">
    <title>
        {% block title %}
            博客首页
        {% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--  Icon Font stylesheet  -->
    <link href="{% static 'assets/css/icofont.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/font-awesome.css' %}" rel="stylesheet">
    <!--   Common stylesheet  -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <!--   Custom stylesheet  -->
    <link href="{% static 'assets/css/blog.css' %}" rel="stylesheet">
    <!--   Responsive stylesheet  -->
    <link href="{% static 'assets/css/responsive.css' %}" rel="stylesheet">
    {% block headlink %}

    {% endblock %}
</head>

<body>

{% block nav %}

{% endblock %}


{% block content %}

{% endblock %}


{% block footer %}

{% endblock %}


{% block footerjs %}
<script src="{% static 'assets/js/jquery-3.3.1.slim.min.js' %}"></script>
{% endblock %}

<!-- Bootstrap core JavaScript
================================================== -->

<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<!--  Custom js  -->
<script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>