blog/apps/article/urls.py
from django.conf.urls import url
from article.views import Home, Publish, Summernoteimg,Details,Post_commentView

urlpatterns = [
    # 首页
    url(r'^$', Home.as_view(), name='home'),
    # 发帖页面
    url(r'^publish/$', Publish.as_view(), name='publish'),
    # summernote编辑器上传图片
    url(r'^summernoteimg/$', Summernoteimg.as_view(), name='summernoteimg'),
    # 详情
    url(r'^details/(?P<id>\d+)$', Details.as_view(), name='details'),
    # 评论
    url(r'^comment/(?P<post_pk>[0-9]+)/$', Post_commentView.as_view(), name='文章评论'),

]

blog/apps/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

blog/apps/user/urls.py
from django.conf.urls import url

from user.views import Login, Register

urlpatterns = [
    url(r'^login/$', Login.as_view(), name='login'),  # 登录
    url(r'^register/$', Register.as_view(), name='register'),  # 注册
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # summernote富文本编辑器
    url(r'^summernote/', include('django_summernote.urls')),
    # 上传部件自动调用的上传地址,ckeditor富文本编辑器
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 文章（帖子）
    url(r'^', include('article.urls', namespace='article')),
    # 用户
    url(r'^user/', include('user.urls', namespace='user')),
]

blog/apps/article/models.py
# 引入验证，最大值（长度），最小（长度），正则验证
# Create your models here.
from django.core.validators import MinValueValidator, MaxValueValidator, MaxLengthValidator, MinLengthValidator, \
    RegexValidator
# 引入继承
from django.db import models
# 引入基础类
from db.base_model import BaseModel
# 引入富文本字段
from ckeditor_uploader.fields import RichTextUploadingField


# 标签表
class TagModels(BaseModel):
    tagname = models.CharField(max_length=15, validators=[MinLengthValidator(2)], verbose_name='标签名')
    parent = models.ForeignKey(to='self', default=0, null=True, blank=True, verbose_name='父id')

    def __str__(self):
        return self.tagname

    class Meta:
        db_table = "tag"  # 表名
        verbose_name = '标签表'
        verbose_name_plural = verbose_name


# 文章表（贴子）
class ArticleModels(BaseModel):
    # 标题
    articletitle = models.CharField(max_length=50, validators=[MinLengthValidator(2)], verbose_name='文章标题')
    # 属于哪个标签
    tagid = models.ForeignKey(to='TagModels', verbose_name='标签')
    # 作者
    author = models.ForeignKey(to='user.UserModels', verbose_name='作者')
    # 富文本
    articlecontent = RichTextUploadingField(verbose_name='文章详情')

    def __str__(self):
        return self.articletitle

    class Meta:
        db_table = "article"  # 表名
        verbose_name = '文章表'
        verbose_name_plural = verbose_name



# 评论模型
class Comment(BaseModel):
    text = models.TextField(verbose_name='评论内容')
    post = models.ForeignKey('ArticleModels', verbose_name='评论文章')
    # 一对多
    users = models.ForeignKey('user.UserModels', verbose_name='评论人')

    def __str__(self):
        return self.text[:20]

    class Meta:
        db_table = "comment"  # 表名
        verbose_name = "评论区管理"
        verbose_name_plural = verbose_name

blog/apps/article/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from article.models import ArticleModels, Comment


# 发布帖子
class SummernoteForm(forms.ModelForm):
    tagid = forms.IntegerField()
    editordata = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = ArticleModels
        fields = ['articletitle']
        widgets = {
            'editordata': SummernoteInplaceWidget(),
        }


# 评论
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [ 'text']

blog/apps/article/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views import View

from article.forms import SummernoteForm, CommentForm
from article.models import TagModels, ArticleModels, Comment
from user.models import UserModels
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# 首页
class Home(View):
    def get(self, request):
        # 是什么类型的标签
        tag = ['python', '前端', 'JAVA', 'php', 'NET', '数据库', '测试', 'C++']
        tagname = int(request.GET.get('tagname', -1))
        if tagname == -1:
            article = ArticleModels.objects.filter(is_delete=False)
        elif tag[tagname]:
            # 把指定标签下的帖子放入article
            article = []
            parenttag = TagModels.objects.get(tagname=tag[tagname], is_delete=False)
            childrentag = TagModels.objects.filter(parent=parenttag, is_delete=False)
            artiparent = ArticleModels.objects.filter(tagid=parenttag, is_delete=False)
            if artiparent.exists():
                article.append(artiparent[0])
            for i in childrentag:
                artichild = ArticleModels.objects.filter(tagid=i, is_delete=False)
                article = article + list(artichild)
        else:
            return HttpResponse('没有此标签')

        # Paginator 实现分页
        paginator = Paginator(article, 6)
        # 获取当前页面的页码
        page = request.GET.get('page', 1)

        # 获取对应页码的数据
        try:
            itemss = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数，（是小数或字母） 显示第一页
            itemss = paginator.page(1)
        except EmptyPage:
            # 页码为超出范围 显示最后一页
            itemss = paginator.page(paginator.num_pages)

        tags = TagModels.objects.filter()
        # 合成响应    准备数据渲染页面
        context = {
            # 贴子数据
            "article": itemss,
            # 主标签下标
            "tagindex": tagname,
            # 标签名字
            "tagname": tag[tagname],
            # 所有标签
            "tag": tags,
        }
        return render(request, 'article/index.html', context=context)


# 发帖
class Publish(View):
    def get(self, request):
        tag = TagModels.objects.filter()
        islogin = request.session.get('nickname', '')
        context = {
            'tag': tag,
            'islogin': islogin,
        }
        return render(request, 'article/publish.html', context=context)

    def post(self, request):
        userid = request.session.get('id', '')
        data = request.POST
        form = SummernoteForm(data)
        if form.is_valid():
            # 如果用户不存在
            try:
                user = UserModels.objects.get(pk=userid)
            except:
                tag = TagModels.objects.filter()
                islogin = request.session.get('nickname', '')
                context = {
                    'tag': tag,
                    'islogin': islogin,
                    'msg': '用户不存在'
                }
                return render(request, 'article/publish.html', context=context)
            cleane_data = form.cleaned_data
            tagid = cleane_data['tagid']
            # 处理如果tagdata不存在
            try:
                tagdata = TagModels.objects.get(pk=tagid)
            except:
                context = {
                    'form': form,
                    'msg': '没有所属标签',
                }
                return render(request, 'article/publish.html', context=context)
            articletitle = cleane_data['articletitle']
            editordata = cleane_data['editordata']
            ArticleModels.objects.create(articletitle=articletitle, tagid=tagdata, author=user,
                                         articlecontent=editordata)

            # 保存数据完了应该跳到详情页面，但是现在还没有详情页，先跳到本页面
            tag = TagModels.objects.filter()
            islogin = request.session.get('nickname', '')
            context = {
                'tag': tag,
                'islogin': islogin,
            }
            return render(request, 'article/publish.html', context=context)
        else:
            context = {
                'form': form,
            }
            return render(request, 'article/publish.html', context=context)


# Summernote富文本上传图片
class Summernoteimg(View):
    def get(self, request):
        return HttpResponse('发帖！get')

    def post(self, request):
        request = request.POST
        return JsonResponse({'fatie': 'post'})


# 详情
class Details(View):
    def get(self, request, id):
        try:
            artic = ArticleModels.objects.get(pk=id)
        except:
            return HttpResponse('没有此文章')
        myartic = ArticleModels.objects.filter(author=artic.author)
        comment_list = Comment.objects.filter(post_id=id, is_delete=False)
        context = {'artic': artic, 'myartic': myartic, 'comment_list': comment_list}
        return render(request, 'article/details.html', context=context)


# 发表评论
class Post_commentView(View):
    def post(self, request, post_pk):
        try:
            post = ArticleModels.objects.filter(pk=post_pk,
                                                is_delete=False
                                                )
        except ArticleModels.DoesNotExist:
            return redirect('article:home')

        # 接收参数
        data = request.POST
        form = CommentForm(data)

        # 接收用户的id
        user_id = request.session.get("id")
        # 验证数据的合法性
        if form.is_valid():
            # 获取清洗后的数据
            cleaned = form.cleaned_data
            # 取出清洗后的评论
            text = cleaned.get('text')
            # 保存到数据库
            Comment.objects.create(text=text, post_id=post_pk, users_id=user_id)

            artic = ArticleModels.objects.get(pk=post_pk)
            myartic = ArticleModels.objects.filter(author=artic.author_id)
            comment_list = Comment.objects.filter(post_id=post_pk, is_delete=False)
            context = {'artic': artic, 'myartic': myartic, 'comment_list': comment_list}
            return render(request, 'article/details.html', context=context)
        else:
            artic = ArticleModels.objects.get(pk=post_pk)
            myartic = ArticleModels.objects.filter(author=artic.author_id)
            comment_list = Comment.objects.filter(post_id=post_pk, is_delete=False)
            context = {'artic': artic, 'myartic': myartic, 'form': form, 'comment_list': comment_list}
            return render(request, 'article/details.html', context=context)

blog/templates/article/details.html
{% extends 'commen/parent.html' %}
{% load static %}

{% block title %}
    详情
{% endblock %}
{% block headlink %}
    <style>
        .comment-area {
            padding: 0 30px 0;
        }

        .comment-form {
            margin-top: 15px;
        }

        .comment-form .comment-btn {
            background-color: #fff;
            border: 1px solid #aaa;
            font-size: 16px;
            padding: 5px 10px;
        }

        .comment-list-panel {
            margin-top: 30px;
        }

        .comment-list {
            margin-top: 15px;
        }

        .comment-item:not(:last-child) {
            border-bottom: 1px #ccc solid;
            margin-bottom: 20px;
            padding-bottom: 20px;
        }

        .comment-item .nickname,
        .comment-item .submit-date {
            color: #777;
            font-size: 14px;
        }

        .comment-item .nickname:after {
            content: ' ·';
        }

        .comment-item .text {
            padding-top: 5px;
            font-size: 16px;
        }

    </style>
{% endblock %}

{% block nav %}
    {% include 'commen/header.html' %}
{% endblock %}


{% block content %}
    <div class="page-header jumbotron p-3 p-md-5 text-white">
        <div class="dark-overlay"></div>
        <div class="container">
            <div class="col-md-6 px-0 mx-auto ">
                <div class="text-center page-banner-coontent">
                    <h2>分享是奉献的果实</h2>
                    <p>分享（fēnxiǎng）的果实真甜！</p>
                </div>
            </div>
        </div>
    </div>

    <main class="container">
        <div class="row">
            <!-- blog-main SIDEBAR RIGHT -->
            <aside class="col-md-4 blog-sidebar col-sm-5">
                <div class="p-3 mb-3 bg-light rounded text-center">
                    <div class="sidebar-about">
                        <div class="about-img">
                            <img src="{{ MEDIA_URL }}{{ artic.author.head }}" alt="" class="img-fluid rounded-circle">
                        </div>
                        <h4 class="py-2">作者简介</h4>
                        <p class="mb-3">
                        <p>昵称：{{ artic.author.nickname }}</p>
                        <em>个人介绍：</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia
                        bibendum nulla sed consectetur.（以后2.0版本，个人中心可修改个人资料）</p>

                    </div>
                </div>
                <div class="py-3">
                    <div class="sidebar-block">
                        <h4 class="sidebar-title">历史贴子</h4>
                        <ol class="list-unstyled mb-0">
                            {% for foo in myartic %}
                                <li><a href="{% url 'article:details' foo.pk %}">贴子：{{ foo.articletitle }}</a></li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </aside>
            <!-- /.blog-sidebar -->
            <!--  -->

            <div class="col-md-8 blog-main col-sm-7">
                <div class="blog-post">
                    <p class="blog-post-cat">标签:{{ artic.tagid.tagname }}</p>
                    <a href="#">
                        <h2 class="blog-post-title">标题:{{ artic.articletitle }}</h2>
                    </a>
                    <p class="blog-post-meta"> 创建时间：{{ artic.add_time }}</p>
                    <div>{{ artic.articlecontent|safe }}</div>
                </div>
                {#            发表评论#}
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'article:文章评论' artic.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea class="form-control" rows="5" name="text" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>
                    </form>

                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                                <li class="comment-item">
                                    <span class="nickname">{{ comment.users.nickname }}:</span>
                                    <img style="height: 50px;" src="{{ MEDIA_URL }}{{ comment.users.head }}" alt="">
                                    <time class="submit-date"
                                          datetime="">{{ comment.add_time }}
                                    </time>
                                    <div class="text">
                                        评论：{{ comment.text }}
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </section>
            </div>
            <!-- /.blog-main -->
        </div>
        <!-- /.row -->

    </main>
{% endblock %}



{% block footer %}
    {% include 'commen/footer.html' %}
{% endblock %}

blog/templates/article/index.html
{% extends 'commen/parent.html' %}
{% load static %}


{% block title %}
    博客首页
{% endblock %}


{% block nav %}
    {% include 'commen/header.html' %}
{% endblock %}


{% block content %}
    <div class="banner-bg jumbotron p-3 p-md-5 text-white">
        <div class="dark-overlay"></div>
        <div class="container">
            <div class="col-md-8 px-0 mx-auto ">
                <div class="text-center main-banner-coontent">
                    <h1 class="display-4 text-white">欢迎来到娟娟的个人博客</h1>
                    <p class="my-3">学习总是在一点一滴中积累而成的，就像砌砖一样。让我们一起在娟娟博客一起成长吧！加油！成功是属于努力的人！</p>
                    <a href="{% url 'user:register' %}" class="btn btn-danger mt-3 btn-rounded">加入这个大家庭</a>
                </div>
            </div>
        </div>
    </div>

    <main class="container">
        <div class="row">
            <div class="col-md-8 blog-main col-sm-7">

                <div class="blog-post">
                    <a href="#">
                        <h2 class="blog-post-title">不忘初心！</h2>
                    </a>


                    <p class="blog-post-meta"><img src="{% static 'assets/images/blog/la.jpg' %}" alt=""
                                                   class="img-fluid small">2019-02-09</p>
                    <p> 为他人，也为自己，为了技术点做点贡献。
                        如果，大家以为这只是一个技术论坛，那你就错了。站长本人觉得除了技术以外，我们更多的是用技术去改变我们的生活。要说我们技术为啥，我想说，那肯定是为了更好的生活。所以，本论坛除技术交流外，专门开了一个热爱分享的版块。我希望能和大家一起来分享我们技术人的生活，及他们的世界。欢迎，大家的加入
                        ^_^ ^_^ 人生的意义：活出自己的本色。 让我们一起来让自己的人生更加精彩。程序员，写文章，大家见笑了，欢迎吐槽 ^_^ ^_^ ^_^ ，本人微信及电话：15002855529</p>

                </div>
                <!-- /.blog-post -->
                {% for foo in article %}
                    <div class="blog-post">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="blog-post-thumbnail-zone">
                                    <img src="{{ MEDIA_URL }}{{ foo.author.head }}" alt="" class="img-fluid">
                                </div>
                            </div>
                            <div class=" col-lg-6">
                                <div class="blog-post-content ">
                                    <p class="blog-post-cat mt0">标签----{{ foo.tagid.tagname }}</p>
                                    <a href="#">
                                        <h3>标题:{{ foo.articletitle }}</h3>
                                    </a>
                                    <p class="blog-post-meta">发布时间：{{ foo.add_time }}</p>
                                    <div style="height: 155px;overflow: hidden;text-overflow:ellipsis;white-space: nowrap;">
                                        <p style="overflow: hidden;text-overflow:ellipsis;white-space: nowrap;">{{ foo.articlecontent|safe }}</p>
                                    </div>

                                    <a href="{% url 'article:details' foo.pk %}" class="read-more">详情</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


                <nav aria-label="navigation ">
                    <ul class="pagination blog-pagination justify-content-end">
                        {% if article.has_previous %}
                            <li class="page-item disabled">
                                <a class="page-link"
                                   href="{% url 'article:home' %}?page={{ article.previous_page_number }}&tagname={{ tagindex }}"
                                   tabindex="-1">Older</a>
                            </li>
                        {% endif %}
                        {% for p in article.paginator.page_range %}
                            <li class="page-item"><a class="page-link"
                                                     href="{% url 'article:home' %}?page={{ p }}&tagname={{ tagindex }}">{{ p }}</a>
                            </li>
                        {% endfor %}
                        {% if article.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'article:home' %}?page={{ article.next_page_number }}&tagname={{ tagindex }}">Newer</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <!-- /.blog-main -->


            <!-- blog-main SIDEBAR RIGHT -->
            <aside class="col-md-4 blog-sidebar col-sm-5">

                <div class="p-3 mb-3 bg-light rounded text-center">
                    <div class="top-header ">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inlineFormInputGroupUsername"
                                   placeholder="请输入文章关键字">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-search"></i></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="p-3 mb-3 bg-light rounded text-center">
                    <div class="sidebar-about">
                        <div class="about-img">
                            <img src="{% static 'assets/images/blog/la.jpg' %}" alt=""
                                 class="img-fluid rounded-circle">
                        </div>
                        <h4 class="py-2">Hi! -这是我！</h4>
                        <p class="mb-3">欲善其事，必先利其器。始终坚持天道酬勤的原则，一日三省，自信品格的日趋完善，勇于行事，务实求新。三更灯火，寒窗苦读，相信会学有所成。</p>

                        <ul class="list-inline social-link">
                            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-rss"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="py-3">
                    <div class="sidebar-block latest-post">
                        <h4 class="sidebar-title">最新帖子</h4>
                        <ol class="list-unstyled">
                            <li>
                                <a href="#">
                                    <div class="rpost-img">
                                        <img src="{% static 'assets/images/blog/widget-4.jpg' %}" alt=""
                                             class="img-fluid">
                                    </div>
                                    <h5>High Fashion Black and White Photoshoot Art</h5>
                                    <p class="text-muted">20 June 2018 </p>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="rpost-img">
                                        <img src="{% static 'assets/images/blog/widget-2.jpg' %}" alt=""
                                             class="img-fluid">
                                    </div>
                                    <h5>Spanish Women are the Epitome of Beautiful</h5>
                                    <p class="text-muted">20 June 2018 </p>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="rpost-img">
                                        <img src="{% static 'assets/images/blog/widget-3.jpg' %}" alt=""
                                             class="img-fluid">
                                    </div>
                                    <h5>Beauty you lIfe with natural</h5>
                                    <p class="text-muted">20 June 2018</p>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="rpost-img">
                                        <img src="{% static 'assets/images/blog/widget-1.jpg' %}" alt=""
                                             class="img-fluid">
                                    </div>
                                    <h5>Spanish Women are the Epitome of Beautiful</h5>
                                    <p class="text-muted">20 June 2018</p>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>


                <div class="py-3">
                    <div class="sidebar-block instagram">
                        <h4 class="sidebar-title">Top 博主</h4>

                        <div class="instgram-posts">
                            <a href="#"><img src="{% static 'assets/images/blog/widget-1.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-2.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-3.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-4.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-1.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-2.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-3.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-4.jpg' %}" alt=""
                                             class="img-fluid"></a>
                            <a href="#"><img src="{% static 'assets/images/blog/widget-1.jpg' %}" alt=""
                                             class="img-fluid"></a>
                        </div>
                    </div>
                </div>

                <div class="py-3">
                    <div class="">
                        <h4 class="sidebar-title">标签</h4>
                        <div class="list-unstyled mb-0 tags-cloud">
                            {% for foo in tag %}
                                <a href="#">{{ foo.tagname }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>

            </aside>
            <!-- /.blog-sidebar -->
        </div>
        <!-- /.row -->

    </main>
    <!-- /.container -->
{% endblock %}



{% block footer %}
    {% include 'commen/footer.html' %}
{% endblock %}